#[cfg(not(feature = "std"))]
use alloc::{vec, vec::Vec};

use ark_ec::{pairing::Pairing, CurveGroup};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_std::UniformRand;
use digest::Digest;
use rand_core::CryptoRngCore;

const DST_G1_GENERATOR: &[u8] = b"PS-SIG-V1-G1-GENERATOR";
const DST_G2_GENERATOR: &[u8] = b"PS-SIG-V1-G2-GENERATOR";

/// Signing key for PS signature scheme
#[derive(Clone, Debug, CanonicalSerialize, CanonicalDeserialize)]
pub struct Sigkey<E: Pairing> {
    pub x: E::ScalarField,
    pub y: Vec<E::ScalarField>,
}

/// Verification key for PS signature scheme
#[derive(Clone, Debug, CanonicalSerialize, CanonicalDeserialize)]
pub struct Verkey<E: Pairing> {
    pub X_tilde: E::G2Affine,
    pub Y_tilde: Vec<E::G2Affine>,
}

/// Parameters generated by random oracle.
/// These are shared by signer and all users.
#[derive(Clone, Debug, CanonicalSerialize, CanonicalDeserialize)]
pub struct Params<E: Pairing> {
    pub g: E::G1Affine,
    pub g_tilde: E::G2Affine,
}

impl<E: Pairing> Params<E> {
    /// Generate g (G1) and g_tilde (G2) deterministically from a label.
    /// Uses hash-to-curve with domain separation.
    pub fn new<H: Digest>(label: &[u8]) -> Self {
        let g = hash_to_g1::<E, H>(label, DST_G1_GENERATOR);
        let g_tilde = hash_to_g2::<E, H>(label, DST_G2_GENERATOR);
        Self { g, g_tilde }
    }
}

/// Generate signing and verification keys for scheme from 2016 paper
pub fn keygen<E: Pairing, R: CryptoRngCore>(
    count_messages: usize,
    params: &Params<E>,
    rng: &mut R,
) -> (Sigkey<E>, Verkey<E>) {
    let x = E::ScalarField::rand(rng);
    let X_tilde = (params.g_tilde * x).into_affine();
    let mut y = Vec::with_capacity(count_messages);
    let mut Y_tilde = Vec::with_capacity(count_messages);
    for _ in 0..count_messages {
        let y_i = E::ScalarField::rand(rng);
        Y_tilde.push((params.g_tilde * y_i).into_affine());
        y.push(y_i);
    }
    (Sigkey { x, y }, Verkey { X_tilde, Y_tilde })
}

/// Generate signing and verification keys for scheme from 2018 paper.
/// The signing and verification keys will have 1 extra element for m'
pub fn keygen_2018<E: Pairing, R: CryptoRngCore>(
    count_messages: usize,
    params: &Params<E>,
    rng: &mut R,
) -> (Sigkey<E>, Verkey<E>) {
    keygen(count_messages + 1, params, rng)
}

/// Hash to G1 with domain separation
fn hash_to_g1<E: Pairing, H: Digest>(label: &[u8], dst: &[u8]) -> E::G1Affine {
    let mut hasher = H::new();
    hasher.update(label);
    hasher.update(dst);
    let hash = hasher.finalize();

    // Use hash output as seed for deterministic generator
    let mut seed = [0u8; 32];
    let hash_bytes = hash.as_slice();
    let copy_len = core::cmp::min(hash_bytes.len(), 32);
    seed[..copy_len].copy_from_slice(&hash_bytes[..copy_len]);

    let mut rng = crate::deterministic_rng_from_seed(seed);
    E::G1::rand(&mut rng).into_affine()
}

/// Hash to G2 with domain separation
fn hash_to_g2<E: Pairing, H: Digest>(label: &[u8], dst: &[u8]) -> E::G2Affine {
    let mut hasher = H::new();
    hasher.update(label);
    hasher.update(dst);
    let hash = hasher.finalize();

    // Use hash output as seed for deterministic generator
    let mut seed = [0u8; 32];
    let hash_bytes = hash.as_slice();
    let copy_len = core::cmp::min(hash_bytes.len(), 32);
    seed[..copy_len].copy_from_slice(&hash_bytes[..copy_len]);

    let mut rng = crate::deterministic_rng_from_seed(seed);
    E::G2::rand(&mut rng).into_affine()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_bls12_381::Bls12_381;
    use ark_std::rand::{rngs::StdRng, SeedableRng};
    use sha2::Sha256;

    #[test]
    fn test_keygen() {
        fn check<E: Pairing>() {
            let count_msgs = 5;
            let params = Params::<E>::new::<Sha256>(b"test");
            let mut rng = StdRng::seed_from_u64(0u64);
            let (sk, vk) = keygen(count_msgs, &params, &mut rng);
            assert_eq!(sk.y.len(), count_msgs);
            assert_eq!(vk.Y_tilde.len(), count_msgs);
        }

        check::<Bls12_381>();
    }

    #[test]
    fn test_keygen_2018() {
        fn check<E: Pairing>() {
            let count_msgs = 5;
            let params = Params::<E>::new::<Sha256>(b"test");
            let mut rng = StdRng::seed_from_u64(0u64);
            let (sk, vk) = keygen_2018(count_msgs, &params, &mut rng);
            assert_eq!(sk.y.len(), count_msgs + 1);
            assert_eq!(vk.Y_tilde.len(), count_msgs + 1);
        }

        check::<Bls12_381>();
    }
}
